### ISSUE TITLE
No module named 'woob.tools.url'

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/kresus_ynh#151]
### Describe the bug

I do not have any automatic updates, and on some banks, there is an error on manual update.

### Context

- Hardware: Computer
- YunoHost version: 11.1.10 (stable)
- I have access to my server: Through SSH + through the webadmin + direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master

### Steps to reproduce

I do not have any steps to reproduce, all I see is that it may be linked to "la banque postale" (bp), because it uses `woob.tools.url`.
I am not sure at all if this is an installation problem here (missing module) or a Woob problem (module needs an upgrade).

note : This is not a new problem, but I was procrastinating about doing something about it for maybe some months…

I tried to upgrade woobs, but still have this error.

### Logs
```
[2023-02-24T16:25:37.076] [INFO] HTTP - GET /kresus/api/all/ - 304 (738 ms)
[2023-02-24T16:25:45.377] [INFO] HTTP - PUT /kresus/api/operations/2980 - 200 (66 ms)
[2023-02-24T16:25:57.046] [INFO] HTTP - PUT /kresus/api/operations/2900 - 200 (74 ms)
[2023-02-24T16:26:05.449] [INFO] HTTP - PUT /kresus/api/operations/2901 - 200 (23 ms)
[2023-02-24T16:26:14.152] [INFO] providers/woob - Calling woob: command operations...
[2023-02-24T16:26:15.004] [INFO] providers/woob - exited with code 1.
[2023-02-24T16:26:15.005] [INFO] providers/woob - Command returned an error code.
[2023-02-24T16:26:15.058] [INFO] providers/woob - Checking that woob is installed and can actually be called…
[2023-02-24T16:26:15.059] [INFO] providers/woob - Calling woob: command test...
[2023-02-24T16:26:15.799] [INFO] providers/woob - exited with code 0.
[2023-02-24T16:26:15.803] [INFO] providers/woob - OK: woob exited normally with non-empty JSON content.
[2023-02-24T16:26:15.803] [ERROR] providers/woob - Got error while running command "operations": Unable to load module bp.
Traceback (most recent call last):
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 170, in load_module
    pymodule = importlib.import_module('woob_modules.%s' % module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/kresus/data/woob-data/modules/3.1/woob_modules/bp/__init__.py", line 20, in <module>
    from .module import BPModule
  File "/var/www/kresus/data/woob-data/modules/3.1/woob_modules/bp/module.py", line 37, in <module>
    from .browser import BPBrowser, BProBrowser
  File "/var/www/kresus/data/woob-data/modules/3.1/woob_modules/bp/browser.py", line 46, in <module>
    from woob.tools.url import get_url_param
ModuleNotFoundError: No module named 'woob.tools.url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 949, in main
    woob_connector.create_backend(bank_module, params, session)
  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 527, in create_backend
    self.backend = self.woob.build_backend(
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/woob.py", line 450, in build_backend
    return super(Woob, self).build_backend(module_name, params, storage, name, nofail)
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/woob.py", line 105, in build_backend
    module = self.modules_loader.get_or_load_module(module_name)
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 135, in get_or_load_module
    self.load_module(module_name)
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 175, in load_module
    raise ModuleLoadError(module_name, e)
woob.exceptions.ModuleLoadError: No module named 'woob.tools.url'

[2023-02-24T16:26:15.803] [ERROR] providers/woob - 	(error code: UNKNOWN_WOOB_MODULE)
[2023-02-24T16:26:15.848] [ERROR] helpers - when fetching operations: Unable to load module bp.
Traceback (most recent call last):
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 170, in load_module
    pymodule = importlib.import_module('woob_modules.%s' % module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/kresus/data/woob-data/modules/3.1/woob_modules/bp/__init__.py", line 20, in <module>
    from .module import BPModule
  File "/var/www/kresus/data/woob-data/modules/3.1/woob_modules/bp/module.py", line 37, in <module>
    from .browser import BPBrowser, BProBrowser
  File "/var/www/kresus/data/woob-data/modules/3.1/woob_modules/bp/browser.py", line 46, in <module>
    from woob.tools.url import get_url_param
ModuleNotFoundError: No module named 'woob.tools.url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 949, in main
    woob_connector.create_backend(bank_module, params, session)
  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 527, in create_backend
    self.backend = self.woob.build_backend(
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/woob.py", line 450, in build_backend
    return super(Woob, self).build_backend(module_name, params, storage, name, nofail)
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/woob.py", line 105, in build_backend
    module = self.modules_loader.get_or_load_module(module_name)
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 135, in get_or_load_module
    self.load_module(module_name)
  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 175, in load_module
    raise ModuleLoadError(module_name, e)
woob.exceptions.ModuleLoadError: No module named 'woob.tools.url'

[2023-02-24T16:26:15.848] [INFO] helpers - Error
    at new KError (/var/www/kresus/build/server/helpers.js:59:22)
    at callWoob (/var/www/kresus/build/server/providers/woob/index.js:188:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _fetchHelper (/var/www/kresus/build/server/providers/woob/index.js:245:16)
    at async Object.fetchOperations (/var/www/kresus/build/server/providers/woob/index.js:270:12)
    at async pollTransactions (/var/www/kresus/build/server/lib/accounts-manager.js:215:34)
    at async AccountManager.syncTransactions (/var/www/kresus/build/server/lib/accounts-manager.js:338:24)
    at async fetchOperations (/var/www/kresus/build/server/controllers/accesses.js:205:37)
[2023-02-24T16:26:15.852] [ERROR] HTTP - POST /kresus/api/accesses/2/fetch/operations - 500 (1737 ms)
[2023-02-24T16:26:26.367] [INFO] providers/woob - Calling woob: command version...
[2023-02-24T16:26:27.117] [INFO] providers/woob - exited with code 0.
[2023-02-24T16:26:27.118] [INFO] providers/woob - OK: woob exited normally with non-empty JSON content.
[2023-02-24T16:26:27.121] [INFO] HTTP - GET /kresus/api/instance/woob - 200 (759 ms)

```

**Comment by nicofrand** [comment]
Hi, an upgrade should be available since this morning.
Can you try it? If not available in the app store, can you force the update (that should upgrade woob)?

**Comment by supermamie** [comment]
The upgrade failed, and the restoration failed too :scream: 
Here is the full log, but should I open another issue ?

https://paste.yunohost.org/raw/hiduherota

**Comment by nicofrand** [comment]
EXPKEYSIG 23E7166788B63E1E

Ça vient probablement de là (clé GPG de yarn devenue invalide). Tu peux 
chercher sur le web comment régler ça et réessayer ensuite ?

**Comment by supermamie** [comment]
key updated, backup restored, and upgrade running.
node is killing my server, but I'll wait.

I have to leave the computer, so more information tomorrow, sorry.

**Comment by supermamie** [comment]
The upgrade finished, all accounts are refreshed, so I can close the ticket, thanks a lot !

Morality : I waited for months to ask about my problem, just on the day it was solved, next time I'll wait a little more :-)
