### ISSUE TITLE
two factors auth failure

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/kresus_ynh#155]
### Describe the bug

I can't authenticate to my bank because of a two factor auth issue.
When I enter

### Context

- Hardware: VPS
- YunoHost version: 11.1.10
- I have access to my server: through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: first install 0.18.1~ynh11 (weird, I wanted to install 0.19.2 ...)
- If upgrading, current package version: n/a

### Steps to reproduce

add caisse d'épargne, then enter the code received by sms

### Logs

![Capture d’écran du 2023-03-06 13-56-56](https://user-images.githubusercontent.com/474883/223118303-d935d87e-ad0f-4a95-87ec-31ea8b4f08b4.png)

```
Action CREATE_ACCESS failed with error:  
Object { code: "GENERIC_EXCEPTION", message: `Unknown error: .\nTraceback (most recent call last):\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/pages.py", line 1284, in submit_form\n    form.submit()\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/pages.py", line 373, in submit\n    return self.page.browser.location(self.request, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 857, in location\n    self.page.on_load()\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/pages.py", line 2028, in on_load\n    form.submit()\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/pages.py", line 373, in submit\n    return self.page.browser.location(self.request, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 849, in location\n    response = self.open(*args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 836, in open\n    return super(PagesBrowser, self).open(callback=internal_callback, *args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 700, in open\n    return super().open(req, *args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 405, in open\n    response = self.session.send(preq,\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/sessions.py", line 163, in send\n    return func(*args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/sessions.py", line 156, in func\n    return callback(self, resp)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 400, in inner_callback\n    self.raise_for_status(response)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 463, in raise_for_status\n    raise ServerError(http_error_msg, response=response)\nwoob.browser.exceptions.ServerError: 500 Server Error: Internal Server Error\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 704, in fetch\n    results['values'] = self.get_accounts()\n  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 554, in get_accounts\n    for account in list(self.backend.iter_accounts()):\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/module.py", line 85, in iter_accounts\n    for account in self.browser.get_loans_list():\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/switch.py", line 98, in wrapper\n    return val(*args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/retry.py", line 75, in wrapper\n    ret = cb()\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/retry.py", line 71, in <lambda>\n    cb = lambda: func(browser, *args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 922, in inner\n    return func(browser, *args, **kwargs)\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/browser.py", line 1627, in get_loans_list\n    self.loans = list(self.page.get_loan_list())\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/pages.py", line 1251, in get_loan_list\n    self.submit_form(*form_params)\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/pages.py", line 1287, in submit_form\n    raise BrowserUnavailable()\nwoob.exceptions.BrowserUnavailable\n`, shortMessage: "Unknown error: ." }
```
​
```
Action CREATE_ACCESS failed with error:  
Object { code: null, message: "Assertion error: Expected variable to be defined\nError\n    at panic (/var/www/kresus/build/server/helpers.js:31:46)\n    at unwrap (/var/www/kresus/build/server/helpers.js:44:9)\n    at Function.byCredentials (/var/www/kresus/build/server/models/entities/accesses.js:110:37)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async createAndRetrieveData (/var/www/kresus/build/server/controllers/accesses.js:107:22)\n    at async create (/var/www/kresus/build/server/controllers/accesses.js:180:22)", shortMessage: "Assertion error: Expected variable to be defined\nError\n    at panic (/var/www/kresus/build/server/helpers.js:31:46)\n    at unwrap (/var/www/kresus/build/server/helpers.js:44:9)\n    at Function.byCredentials (/var/www/kresus/build/server/models/entities/accesses.js:110:37)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async createAndRetrieveData (/var/www/kresus/build/server/controllers/accesses.js:107:22)\n    at async create (/var/www/kresus/build/server/controllers/accesses.js:180:22)" }
index.8c196ed9.js:77:4261
```

**Comment by Jibec** [comment]
after forcing the upgrade to 0.19.2, the error remains:

```
Action CREATE_ACCESS failed with error:  
Object { code: "GENERIC_EXCEPTION", message: `Unknown error: .\nTraceback (most recent call last):\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/pages.py", line 1284, in submit_form\n    form.submit()\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/pages.py", line 373, in submit\n    return self.page.browser.location(self.request, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 857, in location\n    self.page.on_load()\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/pages.py", line 2028, in on_load\n    form.submit()\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/pages.py", line 373, in submit\n    return self.page.browser.location(self.request, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 849, in location\n    response = self.open(*args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 836, in open\n    return super(PagesBrowser, self).open(callback=internal_callback, *args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 700, in open\n    return super().open(req, *args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 405, in open\n    response = self.session.send(preq,\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/sessions.py", line 163, in send\n    return func(*args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/sessions.py", line 156, in func\n    return callback(self, resp)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 400, in inner_callback\n    self.raise_for_status(response)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 463, in raise_for_status\n    raise ServerError(http_error_msg, response=response)\nwoob.browser.exceptions.ServerError: 500 Server Error: Internal Server Error\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 706, in fetch\n    results['values'] = self.get_operations(from_date)\n  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 589, in get_operations\n    for account in list(self.backend.iter_accounts()):\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/module.py", line 85, in iter_accounts\n    for account in self.browser.get_loans_list():\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/switch.py", line 98, in wrapper\n    return val(*args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/retry.py", line 75, in wrapper\n    ret = cb()\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/retry.py", line 71, in <lambda>\n    cb = lambda: func(browser, *args, **kwargs)\n  File "/var/www/kresus/venv/lib/python3.9/site-packages/woob/browser/browsers.py", line 922, in inner\n    return func(browser, *args, **kwargs)\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/browser.py", line 1627, in get_loans_list\n    self.loans = list(self.page.get_loan_list())\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/pages.py", line 1251, in get_loan_list\n    self.submit_form(*form_params)\n  File "/var/www/kresus/data/woob-data/modules/3.4/woob_modules/caissedepargne/pages.py", line 1287, in submit_form\n    raise BrowserUnavailable()\nwoob.exceptions.BrowserUnavailable\n`, shortMessage: "Unknown error: ." }
```

**Comment by nicofrand** [comment]
Hi,

Thanks for opening a ticket!

Unfortunately there does not seem to be something I can do from the package perspective, this is an issue with the module from woob.

Regarding the 0.18.2 instead of 0.19.2 I'll check with YunoHost but the catalog seems fine to me:

```
# yunohost app manifest kresus | grep version
  required_yunohost_version: ok
version: 0.19.2~ynh2

```

**Comment by Jibec** [comment]
maybe this is related? https://gitlab.com/woob/woob/-/issues/619

**Comment by nicofrand** [comment]
It probably is indeed. I know valde commented some part of the module (about loans) while waiting for a clean fix.
