### ISSUE TITLE
python-jose not installed during install

### ISSUE THREAD

**Issue by etieng** [YunoHost-Apps/kresus_ynh#186]
### Describe the bug

When installing Kresus for the first time, Woob cannot fetch data due to missing python library _python-jose_

### Context

- Hardware: *VPS @ barebone @ home*
- YunoHost version: 11.2.10.3
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: ZFS raid for yunohost.app directory
- Using, or trying to install package version/branch: stable 0.20.1~ynh3

### Steps to reproduce

- Install Kresus from webmin on _maindomain/kresus_ > **OK**
- setup new bank account on Kresus webpage > **cannot fetch data**
- logs from Kresus said missing python-jose
- Do : `#: sudo -u kresus pip install python-jose`
- setup new bank on Kresus on webpage > **OK**

### Expected behavior

python-jose should be installed during install of Kresus_ynh

### Logs

```
[2024-04-25T11:31:34.162] [INFO] HTTP - POST /***sus/api/settings - 200 (17 ms)
[2024-04-25T11:31:34.459] [INFO] accounts-manager - Retrieve all accounts from access creditcooperatif with login **********
[2024-04-25T11:31:34.467] [INFO] providers/woob - Calling woob: command accounts...
[2024-04-25T11:31:40.586] [INFO] providers/woob - exited with code 1.
[2024-04-25T11:31:40.586] [INFO] providers/woob - Command returned an error code.
[2024-04-25T11:31:40.587] [INFO] providers/woob - Checking that woob is installed and can actually be called…
[2024-04-25T11:31:40.587] [INFO] providers/woob - Calling woob: command test...
[2024-04-25T11:31:41.029] [INFO] providers/woob - exited with code 0.
[2024-04-25T11:31:41.030] [INFO] providers/woob - OK: woob exited normally with non-empty JSON content.
[2024-04-25T11:31:41.030] [ERROR] providers/woob - Got error while running command "3": Unable to load module creditcooperatif.
Traceback (most recent call last):
  File "/var/www/***sus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 281, in check_version
    pkg = pkg_resources.get_distribution(name)
  File "/var/www/***sus/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 497, in get_distribution
    dist = get_provider(dist)
  File "/var/www/***sus/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 384, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/var/www/***sus/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 937, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/www/***sus/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 798, in resolve
    dist = self._resolve_dist(
  File "/var/www/***sus/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 839, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-jose' distribution was not found and is required by the application

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/***sus/build/server/providers/woob/py/main.py", line 924, in main
    woob_connector.create_backend(bank_module, params, session)
  File "/var/www/***sus/build/server/providers/woob/py/main.py", line 525, in create_backend
    self.backend = self.woob.build_backend(
  File "/var/www/***sus/venv/lib/python3.9/site-packages/woob/core/woob.py", line 504, in build_backend
    return super().build_backend(module_name, params, storage, name, nofail, logger)
  File "/var/www/***sus/venv/lib/python3.9/site-packages/woob/core/woob.py", line 141, in build_backend
    module = self.modules_loader.get_or_load_module(module_name)
  File "/var/www/***sus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 197, in get_or_load_module
    self.load_module(module_name)
  File "/var/www/***sus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 239, in load_module
    self.check_version(module_name, module_spec)
  File "/var/www/***sus/venv/lib/python3.9/site-packages/woob/core/modules.py", line 283, in check_version
    raise ModuleLoadError(
woob.exceptions.ModuleLoadError: Module requires python package "python-jose" but not installed.
```

**Comment by nicofrand** [comment]
It should be installed already: https://github.com/YunoHost-Apps/kresus_ynh/blob/2016f08263ee6b4b0a7331bf843f84ff77c92ede/manifest.toml#L62

**Comment by etieng** [comment]
Well, definitely _python3-josepy_ **debian package** was installed
```
2024-04-25 11:25:35,586: DEBUG - Selecting previously unselected package python3-josepy.
2024-04-25 11:25:35,593: DEBUG - Preparing to unpack .../64-python3-josepy_1.2.0-2_all.deb ...
2024-04-25 11:25:35,599: DEBUG - Unpacking python3-josepy (1.2.0-2) ...
>><<
2024-04-25 11:25:40,494: DEBUG - Setting up python3-josepy (1.2.0-2) ...
```
With no errors returned, but at some point _python-jose_ was missing for Woob, as stated in logs of first publication.

How can I investigate further ?

**Comment by nicofrand** [comment]
I don't really know… I kind of remember of a similar issue in the other way (debian package was working, not the one from pip) so I am not eager to replace one by the other :/

**Comment by etieng** [comment]
Ok, if I'm the only one concerned...
I posted to have a record somewhere.

**Comment by tseignette** [comment]
> Yes.
> 
> Thanks for testing and investigating! I'll create a MR to change `python3-josepy` to `python3-jose` then. Or would you be eager to do it :)?

Happy to help :) Yes I can do it tomorrow, and I'll open an issue in Woob
