### ISSUE TITLE
Pas de possibilité de connexion sur le Crédit Agricole depuis le 24 septembre

### ISSUE THREAD

**Issue by JacquelinDV** [YunoHost-Apps/kresus_ynh#196]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

*A clear and concise description of what the bug is.*
DEPUIS mardi 24 septembre je n'ai plus accès au compte Crédit Agricole avec Krésus, il n'y a plus de mises à jour de solde ou d'écriture.

### Context

- Hardware:  Raspberry Pi 3B+ with VPN 
- YunoHost version: 11.2.30.2
- I have access to my server: Through SSH & through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 

- Using package version/branch: 0.21.2~ynh2

### Steps to reproduce

Après chaque essai de mise à jour des comptes au Crédit Agricole, j'ai un message qui dit: 
"Unknown error: 'TokenPage' object has no attribute 'get_url'. Erreur inconnue de Kresus : essayez de mettre à jour Woob, et si cela ne règle pas votre problème, merci de signaler l'erreur aux auteurs de Kresus. Veuillez vous référer à la console développeurs pour plus d'informations."

D'autre part, le diagnostic journalier de Yunohost envoi le message suivant depuis quelque temps:
"=================================
Applications (apps)
=================================

[WARNING] An issue was found for app Banques
  - This application is currently flagged as broken on YunoHost's application catalog. This may be a temporary issue while the maintainers attempt to fix the issue. In the meantime, upgrading this app is disabled."

### Expected behavior

La mise à jour des soldes et des écritures.

### Logs

*When an operation fails, YunoHost provides a simple way to share the logs.*

JOURNALCTL:
- Journal begins at Wed 2024-04-17 19:25:42 CEST, ends at Fri 2024-09-27 19:30:18 CEST. --
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:09,105:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/association/operations/synthese/detail-comptes/jcr:content.n3.operations.json?compteIdx=0&grandeFamilleCode=7&idDevise=EUR&idElementContrat=00000000F5F1F0F9F0F0F5F4F6F4F0 HTTP/11" 200 1926
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:09,109:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/association/operations/synthese/detail-comptes/jcr:content.n3.operations.json?compteIdx=0&grandeFamilleCode=7&idDevise=EUR&idElementContrat=00000000F5F1F0F9F0F0F5F4F6F4F0 with HistoryPage
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:09,681:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/association/operations/synthese.html HTTP/11" 200 48603
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:09,803:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/association/operations/synthese.html with AccountsPage
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:09,908:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/association/operations/synthese/detail-comptes/jcr:content.n3.operations.json?compteIdx=1&grandeFamilleCode=7&idDevise=EUR&idElementContrat=00000000F0F1F5F5F3F0F9F2F6F0F0 HTTP/11" 200 226
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:09,913:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/association/operations/synthese/detail-comptes/jcr:content.n3.operations.json?compteIdx=1&grandeFamilleCode=7&idDevise=EUR&idElementContrat=00000000F0F1F5F5F3F0F9F2F6F0F0 with HistoryPage
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:10,522:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/association/operations/synthese.html HTTP/11" 200 48606
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:10,674:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/association/operations/synthese.html with AccountsPage
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:10,746:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/libs/granite/csrf/token.json HTTP/11" 200 103
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:10,748:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/libs/granite/csrf/token.json with TokenPage
sept. 27 19:23:11 kresus[535]: 2024-09-27 19:23:10,827:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "POST /ca-pyrenees-gascogne/association/operations/moco/catitres/jcr:content.init.html HTTP/11" 500 2242
sept. 27 19:23:11 kresus[535]: [2024-09-27T19:23:11.178] [INFO] providers/woob - Command returned an error code.
sept. 27 19:23:11 kresus[535]: [2024-09-27T19:23:11.179] [INFO] providers/woob - Checking that woob is installed and can actually be called…
sept. 27 19:23:11 kresus[535]: [2024-09-27T19:23:11.180] [INFO] providers/woob - Calling woob: command test...
sept. 27 19:23:13 kresus[535]: [2024-09-27T19:23:13.661] [INFO] providers/woob - exited with code 0.
sept. 27 19:23:13 kresus[535]: [2024-09-27T19:23:13.662] [INFO] providers/woob - OK: woob exited normally with non-empty JSON content.
sept. 27 19:23:13 kresus[535]: [2024-09-27T19:23:13.662] [ERROR] providers/woob - Got error while running command "2": Unknown error: 'TokenPage' object has no attribute 'get_url'.
sept. 27 19:23:13 kresus[535]: Traceback (most recent call last):
sept. 27 19:23:13 kresus[535]:   File "/var/www/kresus/build/server/providers/woob/py/main.py", line 704, in fetch
sept. 27 19:23:13 kresus[535]:     results['values'] = self.get_transactions(from_date)
sept. 27 19:23:13 kresus[535]:   File "/var/www/kresus/build/server/providers/woob/py/main.py", line 593, in get_transactions
sept. 27 19:23:13 kresus[535]:     for hist_tr in self.backend.iter_history(account):
sept. 27 19:23:13 kresus[535]:   File "/home/yunohost.app/kresus/woob-data/modules/3.6/woob_modules/cragr/browser.py", line 1250, in iter_history
sept. 27 19:23:13 kresus[535]:     logged_on_netfinca = self.go_netfinca_space(account)
sept. 27 19:23:13 kresus[535]:   File "/home/yunohost.app/kresus/woob-data/modules/3.6/woob_modules/cragr/browser.py", line 1313, in go_netfinca_space
sept. 27 19:23:13 kresus[535]:     url = self.page.get_url()
sept. 27 19:23:13 kresus[535]: AttributeError: 'TokenPage' object has no attribute 'get_url'
sept. 27 19:23:13 kresus[535]: [2024-09-27T19:23:13.663] [ERROR] providers/woob -         (error code: GENERIC_EXCEPTION)
sept. 27 19:23:13 kresus[535]: [2024-09-27T19:23:13.714] [ERROR] helpers - when fetching transactions: Unknown error: 'TokenPage' object has no attribute 'get_url'.
sept. 27 19:23:13 kresus[535]: Traceback (most recent call last):
sept. 27 19:23:13 kresus[535]:   File "/var/www/kresus/build/server/providers/woob/py/main.py", line 704, in fetch
sept. 27 19:23:13 kresus[535]:     results['values'] = self.get_transactions(from_date)
sept. 27 19:23:13 kresus[535]:   File "/var/www/kresus/build/server/providers/woob/py/main.py", line 593, in get_transactions
sept. 27 19:23:13 kresus[535]:     for hist_tr in self.backend.iter_history(account):
sept. 27 19:23:13 kresus[535]:   File "/home/yunohost.app/kresus/woob-data/modules/3.6/woob_modules/cragr/browser.py", line 1250, in iter_history
sept. 27 19:23:13 kresus[535]:     logged_on_netfinca = self.go_netfinca_space(account)
sept. 27 19:23:13 kresus[535]:   File "/home/yunohost.app/kresus/woob-data/modules/3.6/woob_modules/cragr/browser.py", line 1313, in go_netfinca_space
sept. 27 19:23:13 kresus[535]:     url = self.page.get_url()
sept. 27 19:23:13 kresus[535]: AttributeError: 'TokenPage' object has no attribute 'get_url'
sept. 27 19:23:13 kresus[535]: [2024-09-27T19:23:13.715] [INFO] helpers - Error
sept. 27 19:23:13 kresus[535]:     at new KError (/var/www/kresus/build/server/helpers.js:62:22)
sept. 27 19:23:13 kresus[535]:     at callWoob (/var/www/kresus/build/server/providers/woob/index.js:234:15)
sept. 27 19:23:13 kresus[535]:     at async _fetchHelper (/var/www/kresus/build/server/providers/woob/index.js:291:16)
sept. 27 19:23:13 kresus[535]:     at async Object.fetchTransactions (/var/www/kresus/build/server/providers/woob/index.js:315:12)
sept. 27 19:23:13 kresus[535]:     at async /var/www/kresus/build/server/lib/accounts-manager.js:258:20
sept. 27 19:23:13 kresus[535]:     at async retryCallProvider (/var/www/kresus/build/server/lib/accounts-manager.js:95:20)
sept. 27 19:23:13 kresus[535]:     at async pollTransactions (/var/www/kresus/build/server/lib/accounts-manager.js:257:34)
sept. 27 19:23:13 kresus[535]:     at async AccountManager.syncTransactions (/var/www/kresus/build/server/lib/accounts-manager.js:393:24)
sept. 27 19:23:13 kresus[535]:     at async fetchTransactions (/var/www/kresus/build/server/controllers/accesses.js:209:37)
sept. 27 19:23:13 kresus[535]: [2024-09-27T19:23:13.722] [ERROR] HTTP - POST /kresus/api/accesses/1/fetch/transactions - 500 (55111 ms)

/var/log/kresus/kresus.log
2024-09-27 19:23:09,681:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/association/operations/synthese.html HTTP/11" 200 48603
2024-09-27 19:23:09,803:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/association/operations/synthese.html with AccountsPage
2024-09-27 19:23:09,908:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/association/operations/synthese/detail-comptes/jcr:content.n3.operations.json?compteIdx=1&grandeFamilleCode=7&idDevise=EUR&idElementContrat=00000000F0F1F5F5F3F0F9F2F6F0F0 HTTP/11" 200 226
2024-09-27 19:23:09,913:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/association/operations/synthese/detail-comptes/jcr:content.n3.operations.json?compteIdx=1&grandeFamilleCode=7&idDevise=EUR&idElementContrat=00000000F0F1F5F5F3F0F9F2F6F0F0 with HistoryPage
2024-09-27 19:23:10,522:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/association/operations/synthese.html HTTP/11" 200 48606
2024-09-27 19:23:10,674:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/association/operations/synthese.html with AccountsPage
2024-09-27 19:23:10,746:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "GET /ca-pyrenees-gascogne/libs/granite/csrf/token.json HTTP/11" 200 103
2024-09-27 19:23:10,748:DEBUG:woob.cragr.browser:browsers.py:1004:internal_callback Handle https://www.credit-agricole.fr/ca-pyrenees-gascogne/libs/granite/csrf/token.json with TokenPage
2024-09-27 19:23:10,827:DEBUG:urllib3.connectionpool:connectionpool.py:546:_make_request https://www.credit-agricole.fr:443 "POST /ca-pyrenees-gascogne/association/operations/moco/catitres/jcr:content.init.html HTTP/11" 500 2242
[2024-09-27T19:23:11.178] [INFO] providers/woob - Command returned an error code.
[2024-09-27T19:23:11.179] [INFO] providers/woob - Checking that woob is installed and can actually be called…
[2024-09-27T19:23:11.180] [INFO] providers/woob - Calling woob: command test...
[2024-09-27T19:23:13.661] [INFO] providers/woob - exited with code 0.
[2024-09-27T19:23:13.662] [INFO] providers/woob - OK: woob exited normally with non-empty JSON content.
[2024-09-27T19:23:13.662] [ERROR] providers/woob - Got error while running command "2": Unknown error: 'TokenPage' object has no attribute 'get_url'.
Traceback (most recent call last):
  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 704, in fetch
    results['values'] = self.get_transactions(from_date)
  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 593, in get_transactions
    for hist_tr in self.backend.iter_history(account):
  File "/home/yunohost.app/kresus/woob-data/modules/3.6/woob_modules/cragr/browser.py", line 1250, in iter_history
    logged_on_netfinca = self.go_netfinca_space(account)
  File "/home/yunohost.app/kresus/woob-data/modules/3.6/woob_modules/cragr/browser.py", line 1313, in go_netfinca_space
    url = self.page.get_url()
AttributeError: 'TokenPage' object has no attribute 'get_url'

[2024-09-27T19:23:13.663] [ERROR] providers/woob - 	(error code: GENERIC_EXCEPTION)
[2024-09-27T19:23:13.714] [ERROR] helpers - when fetching transactions: Unknown error: 'TokenPage' object has no attribute 'get_url'.
Traceback (most recent call last):
  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 704, in fetch
    results['values'] = self.get_transactions(from_date)
  File "/var/www/kresus/build/server/providers/woob/py/main.py", line 593, in get_transactions
    for hist_tr in self.backend.iter_history(account):
  File "/home/yunohost.app/kresus/woob-data/modules/3.6/woob_modules/cragr/browser.py", line 1250, in iter_history
    logged_on_netfinca = self.go_netfinca_space(account)
  File "/home/yunohost.app/kresus/woob-data/modules/3.6/woob_modules/cragr/browser.py", line 1313, in go_netfinca_space
    url = self.page.get_url()
AttributeError: 'TokenPage' object has no attribute 'get_url'

[2024-09-27T19:23:13.715] [INFO] helpers - Error
    at new KError (/var/www/kresus/build/server/helpers.js:62:22)
    at callWoob (/var/www/kresus/build/server/providers/woob/index.js:234:15)
    at async _fetchHelper (/var/www/kresus/build/server/providers/woob/index.js:291:16)
    at async Object.fetchTransactions (/var/www/kresus/build/server/providers/woob/index.js:315:12)
    at async /var/www/kresus/build/server/lib/accounts-manager.js:258:20
    at async retryCallProvider (/var/www/kresus/build/server/lib/accounts-manager.js:95:20)
    at async pollTransactions (/var/www/kresus/build/server/lib/accounts-manager.js:257:34)
    at async AccountManager.syncTransactions (/var/www/kresus/build/server/lib/accounts-manager.js:393:24)
    at async fetchTransactions (/var/www/kresus/build/server/controllers/accesses.js:209:37)
[2024-09-27T19:23:13.722] [ERROR] HTTP - POST /kresus/api/accesses/1/fetch/transactions - 500 (55111 ms)

Il est conseillé de mettree à jopur woob (version 3.6), ce qui ne change tien à cela.

**Comment by JacquelinDV** [comment]
La mise à jour woob ne change rien au problème: même erreur à la mise à jour du compte!

**Comment by nicofrand** [comment]
Je ne vois pas comment tu as mis à jour woob comme indiqué.
J'ignore encore si c'est un problème de woob pas à jour ou un problème de connecteur woob.

Es-tu à l'aise avec la ligne de commande, pour tester directement woob par hasard ?

**Comment by nicofrand** [comment]
Closing now that there is an upstream issue: https://gitlab.com/woob/woob/-/issues/734
