### ISSUE TITLE
Connexion ING Impossible

### ISSUE THREAD

**Issue by 1000sabords** [YunoHost-Apps/kresus_ynh#33]
Bonjour,
Depuis le changement du site ING, Kresus ne synchronisait plus les comptes.
J'ai:

sauvegardé mes data Kresus
désinstallé Kresus de Yunohost
réinstallé Kresus (passage weboob 1.5)

mais depuis, impossible de reconnecter Kresus à ING, voici le log:
[2019-04-01T17:19:19.672] [ERROR] sources/weboob - (error code: GENERIC_EXCEPTION) [2019-04-01T17:19:19.673] [ERROR] controllers/accesses - The access process creation failed, cleaning up... 
[2019-04-01T17:19:19.673] [INFO] controllers/accesses - deleting access... [2019-04-01T17:19:19.676] [ERROR] helpers - when creating a bank access: Unknown error: __init__() got an unexpected keyword argument 'browser'. Traceback (most recent call last): File "/var/www/kresus/build/server/weboob/main.py", line 610, in fetch results['values'] = self.get_accounts() File "/var/www/kresus/build/server/weboob/main.py", line 488, in get_accounts for account in list(self.backend.iter_accounts()): File "/var/www/kresus/data/weboob-data/modules/1.5/ing/module.py", line 74, in iter_accounts return self.browser.iter_matching_accounts() File "/var/www/kresus/data/weboob-data/modules/1.5/ing/api_browser.py", line 52, in inner self.do_login() File "/var/www/kresus/data/weboob-data/modules/1.5/ing/api_browser.py", line 153, in do_login 'clickPositions': self.page.get_password_coord(img, self.password) File "/var/www/kresus/data/weboob-data/modules/1.5/ing/api/login.py", line 104, in get_password_coord vk = INGVirtKeyboard(image, 5, 2, browser=self.browser) TypeError: __init__() got an unexpected keyword argument 'browser'

Quand j'essaye d'importer ma sauvegarde j'ai :
[2019-04-01T17:06:50.710] [ERROR] HTTP - POST /kresus/api/v1/all/ - 400 (56 ms) [2019-04-01T17:06:56.360] [INFO] HTTP - GET /kresus/api/v1/logs - 200 (10 ms) [2019-04-01T17:10:56.977] [ERROR] helpers - when importing data: missing parameter "data" in the file [2019-04-01T17:10:56.977] [INFO] helpers - Error at new KError (/var/www/kresus/build/server/helpers.js:76:16) at /var/www/kresus/build/server/controllers/v1/all.js:195:15 at Generator.next (<anonymous>) at asyncGeneratorStep (/var/www/kresus/build/server/controllers/v1/all.js:42:103) at _next (/var/www/kresus/build/server/controllers/v1/all.js:44:194) at /var/www/kresus/build/server/controllers/v1/all.js:44:364 at new Promise (<anonymous>) at /var/www/kresus/build/server/controllers/v1/all.js:44:97 at import_ (/var/www/kresus/build/server/controllers/v1/all.js:186:19) at Layer.handle [as handle_request] (/var/www/kresus/node_modules/express/lib/router/layer.js:95:5)
Merci d'avance.
Cdt.
Alain

**Comment by bnjbvr** [comment]
Merci pour le ticket ! On va regarder ça côté Kresus où un [ticket](https://framagit.org/kresusapp/kresus/issues/847) a également été ouvert.

**Comment by Jibec** [comment]
merci donc pour ce ticket, comme il est pris en charge par l'équipe projet, c'est qu'il n'est pas lié au paquet yunohost. bonne soirée :)
