### ISSUE TITLE
error since last maj 0.16.0~ynh4

### ISSUE THREAD

**Issue by valderaplets** [YunoHost-Apps/kresus_ynh#74]
* * Version 0.16.0~ynh4

during refresh : 

```
[2020-05-30T18:52:37.854] [ERROR] providers/weboob - 	(error code: GENERIC_EXCEPTION)
[2020-05-30T18:52:37.873] [ERROR] helpers - when fetching operations: Unknown error: Symbol '1' not found; all symbol hashes are available in /tmp/weboob_session_ybkcb22g.
Traceback (most recent call last):
  File "/var/www/kresus/build/server/providers/weboob/py/main.py", line 687, in fetch
    results['values'] = self.get_operations(from_date)
  File "/var/www/kresus/build/server/providers/weboob/py/main.py", line 570, in get_operations
    for account in list(self.backend.iter_accounts()):
  File "/var/www/kresus/data/weboob-data/modules/2.0/caissedepargne/module.py", line 73, in iter_accounts
    for account in self.browser.get_accounts_list():
  File "/var/www/kresus/venv/lib/python3.5/site-packages/weboob/browser/switch.py", line 91, in wrapper
    return val(*args, **kwargs)
  File "/var/www/kresus/venv/lib/python3.5/site-packages/weboob/browser/browsers.py", line 821, in inner
    browser.do_login()
  File "/var/www/kresus/data/weboob-data/modules/2.0/caissedepargne/browser.py", line 409, in do_login
    self.do_new_login(data)
  File "/var/www/kresus/data/weboob-data/modules/2.0/caissedepargne/browser.py", line 710, in do_new_login
    feature='login'
  File "/var/www/kresus/data/weboob-data/modules/2.0/caissedepargne/browser.py", line 638, in do_authentication_validation
    AUTHENTICATION_METHODS[authentication_method](**params)
  File "/var/www/kresus/data/weboob-data/modules/2.0/caissedepargne/browser.py", line 603, in do_vk_authentication
    vk = CaissedepargneNewKeyboard(self, images_url)
  File "/var/www/kresus/data/weboob-data/modules/2.0/caissedepargne/pages.py", line 243, in __init__
    super(CaissedepargneNewKeyboard, self).__init__(code_to_filedata)
  File "/var/www/kresus/venv/lib/python3.5/site-packages/weboob/tools/captcha/virtkeyboard.py", line 284, in __init__
    raise VirtKeyboardError("Symbol '%s' not found; all symbol hashes are available in %s" % (char, path))
weboob.tools.captcha.virtkeyboard.VirtKeyboardError: Symbol '1' not found; all symbol hashes are available in /tmp/weboob_session_ybkcb22g
```

**Comment by nicofrand** [comment]
Hi,

this is a weboob issue, which can't be deal by this package, nor Kresus.
I do have it sometimes too, but not always, it's kind of random and should not prevent you to fetch your transactions every time. I'll ask weboob if they have an idea how to fix it though.
