### ISSUE TITLE
Can not sync after Buster upgrade

### ISSUE THREAD

**Issue by kidonsky** [YunoHost-Apps/kresus_ynh#80]
Hello,

After upgrading server to Buster I can not sync data from bank.

The root problem looks to be **_SSL: DH_KEY_TOO_SMALL_**
Here is the shorten log (without long _maybe_ sensitive links) :

> [2020-08-20T22:48:21.220] [INFO] HTTP - GET /kresus/api/all/ - 200 (123 ms)
[2020-08-20T22:48:28.522] [INFO] providers/weboob - Calling weboob: command operations...
[2020-08-20T22:48:30.588] [INFO] providers/weboob - exited with code 0.
[2020-08-20T22:48:30.589] [WARN] providers/weboob - stderr: 2020-08-20 22:48:30,357:WARNING:urllib3.connectionpool:connectionpool.py:752:urlopen Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)'))': /api/oauth/v2/authorize**longurl**
2020-08-20 22:48:30,442:WARNING:urllib3.connectionpool:connectionpool.py:752:urlopen Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)'))': /api/oauth/v2/authorize?**longurl**
[2020-08-20T22:48:30.590] [INFO] providers/weboob - Command returned an error code.
[2020-08-20T22:48:30.591] [ERROR] providers/weboob - Got error while running command "operations": HTTPSConnectionPool(host='mybankhost', port=443): Max retries exceeded with url: /api/oauth/v2/authorize**longurl** (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)')))
[2020-08-20T22:48:30.591] [ERROR] providers/weboob - 	(error code: CONNECTION_ERROR)
[2020-08-20T22:48:30.639] [ERROR] helpers - when fetching operations: HTTPSConnectionPool(host='mybankhost', port=443): Max retries exceeded with url: /api/oauth/v2/**longurl (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)')))
[2020-08-20T22:48:30.640] [INFO] helpers - Error
    at new KError (/var/www/kresus/build/server/helpers.js:59:22)
    at callWeboob (/var/www/kresus/build/server/providers/weboob/index.js:213:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async _fetchHelper (/var/www/kresus/build/server/providers/weboob/index.js:258:16)
    at async Object.fetchOperations (/var/www/kresus/build/server/providers/weboob/index.js:281:12)
    at async AccountManager.retrieveOperationsByAccess (/var/www/kresus/build/server/lib/accounts-manager.js:218:25)
    at async fetchOperations (/var/www/kresus/build/server/controllers/accesses.js:117:43)
[2020-08-20T22:48:30.644] [ERROR] HTTP - GET /kresus/api/accesses/1/fetch/operations - 500 (2148 ms)
[2020-08-20T22:48:37.202] [INFO] providers/weboob - Calling weboob: command version...
[2020-08-20T22:48:37.598] [INFO] providers/weboob - exited with code 0.
[2020-08-20T22:48:37.599] [INFO] providers/weboob - OK: weboob exited normally with non-empty JSON content.
[2020-08-20T22:48:37.604] [INFO] HTTP - GET /kresus/api/settings/weboob - 200 (401 ms) 

I just did the upgrade a hour ago so I forced the sync. I will see with the automated update this night.

So I am on :
- a VPS
- yunohost server v.4.0.4 
- kresus 0.16.0

Thanks

**Comment by nicofrand** [comment]
Hi,

This is not related to kresus or weboob but to your bank's website and your server security configuration, please look at https://forum.yunohost.org/t/kresus-app-please-test/3546/69.

I'll close this ticket as this is not something I can act on, thanks for reporting though.
