### ISSUE TITLE
woob's CrAgr module doesn't work / Woob maybe outdated ?

### ISSUE THREAD

**Issue by CorentinBrule** [YunoHost-Apps/kresus_ynh#94]
In a fresh installation of YunoHost and Kresus, i can't connect my bank account and i have this  message : "Your bank requires a module not supported....."
In Kresus' administration panel, i see "Weboob's version : 2.0" and "successfully updated".
but the current version seems to me to be 2.1 or maybe it comes from the rename of the project in "woob" ?
the CrArg module seems to be still maintained and no other issue is open on the Woob Git about it.

the logs :
```
[2021-04-04T21:00:33.935] [INFO] providers/weboob - Calling weboob: command test...
[2021-04-04T21:00:33.936] [INFO] providers/weboob - Weboob will be updated prior to command "test"
[2021-04-04T21:00:34.327] [INFO] providers/weboob - exited with code 0.
[2021-04-04T21:00:34.327] [INFO] providers/weboob - OK: weboob exited normally with non-empty JSON content.
[2021-04-04T21:00:34.328] [INFO] HTTP - PUT /kresus/api/settings/weboob/ - 200 (393 ms)
[2021-04-04T21:00:37.567] [INFO] HTTP - GET /kresus/api/logs - 200 (6 ms)
[2021-04-04T21:02:12.450] [INFO] accounts-manager - Retrieve all accounts from access cragr with login 00085786382
[2021-04-04T21:02:12.453] [INFO] providers/weboob - Calling weboob: command accounts...
[2021-04-04T21:02:12.657] [INFO] providers/weboob - exited with code 1.
[2021-04-04T21:02:12.657] [INFO] providers/weboob - Command returned an error code.
[2021-04-04T21:02:12.658] [INFO] providers/weboob - Checking that weboob is installed and can actually be called…
[2021-04-04T21:02:12.659] [INFO] providers/weboob - Calling weboob: command test...
[2021-04-04T21:02:12.864] [INFO] providers/weboob - exited with code 0.
[2021-04-04T21:02:12.864] [INFO] providers/weboob - OK: weboob exited normally with non-empty JSON content.
[2021-04-04T21:02:12.865] [ERROR] providers/weboob - Got error while running command "accounts": Unable to load module cragr.
Traceback (most recent call last):
  File "/var/www/kresus/build/server/providers/weboob/py/main.py", line 897, in main
    weboob_connector.create_backend(bank_module, params, session)
  File "/var/www/kresus/build/server/providers/weboob/py/main.py", line 511, in create_backend
    storage=self.storage
  File "/var/www/kresus/venv/lib/python3.7/site-packages/weboob/core/ouiboube.py", line 425, in build_backend
    raise ModuleLoadError(module_name, 'Module does not exist.')
weboob.exceptions.ModuleLoadError: Module does not exist.

[2021-04-04T21:02:12.865] [ERROR] providers/weboob - 	(error code: UNKNOWN_WEBOOB_MODULE)
[2021-04-04T21:02:12.877] [ERROR] controllers/accesses - The access process creation failed, cleaning up...
[2021-04-04T21:02:12.878] [INFO] controllers/accesses - 	deleting access...
[2021-04-04T21:02:12.881] [ERROR] helpers - when creating a bank access: Unable to load module cragr.
Traceback (most recent call last):
  File "/var/www/kresus/build/server/providers/weboob/py/main.py", line 897, in main
    weboob_connector.create_backend(bank_module, params, session)
  File "/var/www/kresus/build/server/providers/weboob/py/main.py", line 511, in create_backend
    storage=self.storage
  File "/var/www/kresus/venv/lib/python3.7/site-packages/weboob/core/ouiboube.py", line 425, in build_backend
    raise ModuleLoadError(module_name, 'Module does not exist.')
weboob.exceptions.ModuleLoadError: Module does not exist.

[2021-04-04T21:02:12.882] [INFO] helpers - Error
    at new KError (/var/www/kresus/build/server/helpers.js:59:22)
    at callWeboob (/var/www/kresus/build/server/providers/weboob/index.js:213:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async _fetchHelper (/var/www/kresus/build/server/providers/weboob/index.js:258:16)
    at async Object.fetchAccounts (/var/www/kresus/build/server/providers/weboob/index.js:272:12)
    at async retrieveAllAccountsByAccess (/var/www/kresus/build/server/lib/accounts-manager.js:45:26)
    at async AccountManager.retrieveNewAccountsByAccess (/var/www/kresus/build/server/lib/accounts-manager.js:128:24)
    at async AccountManager.retrieveAndAddAccountsByAccess (/var/www/kresus/build/server/lib/accounts-manager.js:170:16)
    at async createAndRetrieveData (/var/www/kresus/build/server/controllers/accesses.js:69:9)
    at async create (/var/www/kresus/build/server/controllers/accesses.js:99:22)
[2021-04-04T21:02:12.884] [ERROR] HTTP - POST /kresus/api/accesses/ - 500 (460 ms)
[2021-04-04T21:08:55.673] [INFO] accounts-manager - Retrieve all accounts from access cragr with login 00085786382
```

**Comment by nicofrand** [comment]
Hi!

I have the same issue with the `cragr` module, I'll try and see what's wrong with it and get back to you!

**Comment by bnjbvr** [comment]
Hey, can you try pulling the woob's repository, and retry please? it shoud have been fixed now!

**Comment by nicofrand** [comment]
(you can do that by forcing an upgrade of the package)

**Comment by CorentinBrule** [comment]
I updated woob from the the kresus administration panel and now it's work! Thx !
I did not know where to open the issue but the information circulates quickly!
